# 見通しを良くするため、コメント行を削除
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ASAP_BOX_development

test:
  <<: *default
  database: ASAP_BOX_test

production:
  <<: *default
  database: ASAP_BOX_production
  username: ASAP_BOX
  password: <%= ENV['ASAP_BOX_DATABASE_PASSWORD'] %>
